apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/inject: "disabled"
  name: {{ include "name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    chart: {{ include "chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "name" . }}
  template:
    metadata:
      labels:
        app: {{ include "name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
